// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3yBCccZlIHPOc3W0CNkVpM6y3iGZUarQ',
    appId: '1:784224444720:web:3fa3093bd328e0979ce8f5',
    messagingSenderId: '784224444720',
    projectId: 'izi-bus-df591',
    authDomain: 'izi-bus-df591.firebaseapp.com',
    storageBucket: 'izi-bus-df591.appspot.com',
    measurementId: 'G-13MJDBCFY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe38xnn6Gf9Q4hqh4ADqVfbiQE-I6lORM',
    appId: '1:784224444720:android:952b28f3f860ae8f9ce8f5',
    messagingSenderId: '784224444720',
    projectId: 'izi-bus-df591',
    storageBucket: 'izi-bus-df591.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkHy7K5_Vg2pUVWNDfZnJQ3f_PxoRFn20',
    appId: '1:784224444720:ios:182b146978f5a92e9ce8f5',
    messagingSenderId: '784224444720',
    projectId: 'izi-bus-df591',
    storageBucket: 'izi-bus-df591.appspot.com',
    iosClientId: '784224444720-83k2dnre46oi4e8mlen5or88e6c6d8q4.apps.googleusercontent.com',
    iosBundleId: 'com.example.iziBus',
  );
}
